#%RAML 1.0 Library
usage:
traits:
  transcationalId: !include Traits/common headers trait.raml
  depatureLocationId: !include Traits/queryparm depaturelocationcode trait.raml
  destinationlocationcode: !include Traits/qeryparm destinationlocationcode trait.raml